Migrate snap-guest to qcow2
SatelliteQE/snap-guest pull request #15
Opened 2019-05-06 12:29 UTC by jhutar

Please provide feedback on if this is desired or not. If so, I'll do some actual test :-)

Reason for this is when I want to install the environment on some other host, `*.qcow2` images are almost 100 times smaller thank our `*.img` base images so it is possible to copy them over.

2019-05-06 12:37 UTC, sghai commented
@jhutar thanks

@san7ket @lpramuk do you guys see any challenge/issues if we migrate images from .img to qcow2 ?

2019-05-06 13:04 UTC, san7ket commented
Looks great, and ACK for the move. Although needs testing and @lpramuk do we also need to update the baseOS creation Job?

2019-05-10 08:04 UTC, jhutar commented
Soo, tested with these commands:

```
snap-guest -b rhel76-base -t test-vm -m 2048 -c 2
snap-guest -b rhel76-base -t test-vm-with-swap -m 2048 -c 2 --swap 100
snap-guest -b rhel76-base -t test-vm-cloned -m 2048 -c 2 --clone-image
```

on a system where I have this:

```
# ls /var/lib/libvirt/images/
rhel76-base.qcow2
```

Now I have tried on paprika:

```
# ls /var/lib/libvirt/images/
[...]
rhel76-20181119.0.img  rhel76-base.img
[...]
# /usr/local/bin/2019-05-10-jhutar-snap-guest -b rhel76-base -t test-vm -m 2048 -c 4
```

and works as well, so looks like it is backward compatible (no disk image conversion needed).

2019-05-12 20:15 UTC, lpramuk commented
They are not 100x smaller, raw image occupies the very same place as qcow image, file system is a bit fooled, I admit scp is a bit problem (raw > qcow > scp > qcow > raw) but if this is the only reasoning then this is not enough for me.

The most important reason for using raw images is performance and unless we have perf comparison I cannot even consider this PR.

This PR also forces us to use qcow. I would prefer new option to prefer either qcow or raw.

2019-05-12 20:15 UTC, lpramuk requested changes
See comment

2019-05-14 06:40 UTC, jhutar commented
Ah, right. So this is the measurement:

**My version, VM creation**

```
time snap-guest -b rhel76-base -t test-jhutar --hostname testjhutar.example.com --memory 16384 --cpus 6
```

Two attempts:

```
real    0m10.255s
user    0m1.762s
sys     0m0.326s
```
and:
```
real    0m10.673s
user    0m1.779s
sys     0m0.310s
```

```
# ls /var/lib/libvirt/images/ -alh | grep qcow2
-rw-r--r--.  1 qemu qemu 1.8G May 13 07:38 rhel76-base.qcow2
-rw-r--r--.  1 qemu qemu  67M May 14 02:35 test-jhutar.qcow2
```

**Current version, VM creation**

```
real    0m10.434s
user    0m1.850s
sys     0m0.305s
```

and:

```
real    0m10.235s
user    0m1.788s
sys     0m0.297s
```

```
# ls /var/lib/libvirt/images/ -alh | grep img
-rw-r--r--.  1 qemu qemu 200G May 13 07:42 rhel76-base.img
-rw-r--r--.  1 qemu qemu  54M May 14 02:40 test-jhutar.img
```

Now I'll try to measure Satellite Installation.

2019-05-14 09:00 UTC, jhutar commented
**Current version, yum install satellite**

```
# yum -y install satellite --downloadonly
# time yum -y install satellite
```

```
real    4m17.593s
user    2m35.116s
sys     0m24.185s

real    23m5.618s
user    13m57.927s
sys     3m26.733s
```

**Current version, satellite-installer --scenario satellite**

```
# time satellite-installer --scenario satellite
```

Hmm, I have hit this:
```
/Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[testjhutar.example.com]: Failed to call refresh: Proxy testjhutar.example.com cannot be retrieved: unknown error (response 500)
```

```
real    61m21.365s
user    48m57.395s
sys     3m55.651s
```

2019-05-14 10:19 UTC, jhutar commented
Hmm, BTW on my laptop in VM, satellite pkg installation (plain qcow2 image, no copy on write), it takes:
```
real	9m20.833s
user	4m58.243s
sys	1m27.664s
```
so looks like copy on write is quite expensive.

2019-05-14 11:52 UTC, jhutar commented
**New version, yum install satellite**

```
# yum -y install satellite --downloadonly
# time yum -y install satellite
```

```
real    23m20.124s
user    13m56.266s
sys     3m28.328s
```

**New version, satellite-installer --scenario satellite**

```
# time satellite-installer --scenario satellite
```

Hit same error.

```
real    61m16.300s
user    48m51.651s
sys     3m52.187s
```

2019-05-14 11:53 UTC, jhutar commented
Looks like there is no performance hit. Re-requesting Lukas's review.

2022-11-12 19:21 UTC, closed without merging